name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.1.0
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'pnpm'

      - run: pnpm install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
          version: pnpm ci:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #   NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
